# Generated by Django 4.0.6 on 2022-07-25 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=datetime.datetime(2022, 7, 25, 22, 22, 13, 459923), max_length=200),
        ),
    ]
