# Generated by Django 4.0.6 on 2022-07-26 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2022, 7, 26, 15, 2, 11, 73273), max_length=200),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
